// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgtiqwyovvyqecinapcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNndGlxd3lvdnZ5cWVjaW5hcGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDE4OTcsImV4cCI6MjA2ODA3Nzg5N30.8Ph3Taiw1l0WeAVxxyl2T9W0f7V9Vjjdbqeh5UcTi4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});